#!/bin/sh

# Add untracked files from result of gofmt
for file in $(git diff --name-only | grep -e '\.go$'); do
    git add $file
done
# Add these files back to the previous commit
git commit --amend -C HEAD --no-verify >/dev/null
