#!/bin/sh

echo "Running 'go build', 'go build ./...', and 'go test ./...'"

build_result=$(go build)
build_rc=$?
if [ $build_rc -ne 0 ] ; then
    echo "git pre-commit check failed: build main failed."
    exit 1
fi

build_all_result=$(go build ./...)
build_all_rc=$?
if [ $build_all_rc -ne 0 ] ; then
    echo "git pre-commit check failed: build packages failed."
    exit 1
fi

test_result=$(go test -p 1 ./...)
test_rc=$?
if [ $test_rc -ne 0 ]; then
    echo "git pre-commit check failed: tests failed."
    exit 1
fi
