#!/bin/sh
set -u

# Format code automatically with gofmt
status=0
for file in $(find . | grep -e '\.go$'); do
    gofmt -w $file
done

# Add untracked files from result of gofmt
for file in $(git diff --name-only | grep -e '\.go$'); do
    git add $file
done
# Add these files back to the previous commit
# git commit --amend --no-verify >/dev/null

# Run go build, go build ./..., and go test ./...

build_result=$(go build)
build_rc=$?
if [ $build_rc -ne 0 ] ; then
	echo "git pre-commit check failed: build main failed."
	exit 1
fi

build_all_result=$(go build ./...)
build_all_rc=$?
if [ $build_all_rc -ne 0 ] ; then
	echo "git pre-commit check failed: build packages failed."
	exit 1
fi

test_result=$(go test ./...)
test_rc=$?
if [ $test_rc -ne 0 ]; then
    echo "git pre-commit check failed: tests failed."
    exit 1
fi

